### PR TITLE
Updated process bundle to instantiate apiApplication class using Bund…

### PR DESCRIPTION
**Pull request by ssavu**
…leContext if constructor accepting BundleContext exists.

### CODE REVIEW

**Comment by jkevan** [comment]
It's interesting but how do you manage to pass the bundle context to the API from the Application ?

**Comment by ssavu** [comment]
You can then use SCR annotations to create your api as a service or simply as a component, and have the bundle context available in the activate method.

**Comment by jkevan** [comment]
But what do you do with the bundleContext in the ResourceConfig ?

Since the ResourceConfig is only dealing with classes and not instances, do you have to create some custom factories ?

Do you have a code sample of what is a ResourceConfig (Application) that use the bundleContext in it's own constructor ?

**Comment by ssavu** [comment]
We no longer extend ResourceConfig, instead our ApiApplication directly extends Application.
We can then get our Api main resource and any sub resources using the bundle context, but declaring the resources as components. For an example have a look at:
https://github.com/Jahia/redis-connector/blob/master/src/main/java/org/jahia/modules/redisconnector/api/RCApiApplication.java

**Comment by jkevan** [comment]
looking at the example, the bundle context is only used to retrieve the service instance.

You don't need the bundleContext of your bundle to be able to do that, there is a simpler solution:

import org.jahia.osgi.BundleUtils;

BundleUtils.getOsgiService(RCApi.class, null);

Services are registered in the service registry that is global to every bundles, so the bundle context of your bundle is not the only entry point to retrieve the services you are looking for.

**Comment by jkevan** [comment]
Any answer to my last comment ?

**Comment by ssavu** [comment]
Hey, yes I recently had time to try your solution and I see that works as well. Underneath it just uses FrameworkUtil to retrieve the bundle context. I think both solutions are fine, in the example I gave you we don't make further use of the context. If we did require it, it would be nice, and straight forward, to just have it available in your application class, otherwise you have to know which services you need to call in order to retrieve your actual context.

**Comment by jkevan** [comment]
Ok so for now I will close the pull request as there is no need for the context anymore.
If in the futur you you did require it, just reopen this pull request.

I prefer not introduce new code if there is no need behind, since this new parameter should be documented somewhere and tested it will require time to be finalize.

**Pull request closed without merging**
